{{- if and .Values.options.enableSSL .Values.options.generateCertificates -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "capsule-proxy.fullname" . }}-certgen
  labels:
    {{- include "capsule-proxy.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      name: {{ include "capsule-proxy.fullname" . }}-certgen
      labels:
        {{- include "capsule-proxy.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with $.Values.jobs.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: post-install-job
        image: {{ include "capsule.jobs.certsFullyQualifiedDockerImage" $ }}
        imagePullPolicy: {{ .Values.jobs.certs.pullPolicy }}
        {{- with $.Values.imagePullSecrets }}
        imagePullSecrets:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        args:
            - create
            - --host={{ include "capsule-proxy.certJob.SAN" . }}
            - --namespace=$(NAMESPACE)
            - --secret-name={{ include "capsule-proxy.fullname" . }}
            - --cert-name={{ .Values.options.SSLCertFileName }}
            - --key-name={{ .Values.options.SSLKeyFileName }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- with $.Values.jobs.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      serviceAccountName: {{ include "capsule-proxy.serviceAccountName" . }}
{{- end }}
